name: sbb_oidc_example
description: Demonstrates how to use the sbb_oidc plugin.
publish_to: 'none'
version: 4.0.1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  sbb_oidc:
    path: ../
  # https://pub.dev/packages/collection
  collection: ^1.19.1
  # https://pub.dev/packages/fimber
  fimber: ^0.7.0
  # https://pub.dev/packages/flutter_dotenv
  flutter_dotenv: ^5.2.1
  # https://pub.dev/packages/flutter_json_view
  flutter_json_view: ^1.1.5
  # https://pub.dev/packages/get_it
  get_it: ^8.0.3
  # https://pub.dev/packages/http
  http: ^1.4.0
  # https://pub.dev/packages/meta
  meta: ^1.16.0
  # https://pub.dev/packages/rxdart
  rxdart: ^0.28.0
  # https://pub.dev/packages/sbb_design_system_mobile
  sbb_design_system_mobile: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/esq_mobile_dev.env
    - assets/example_app.env
