name: sbb_oidc_example
description: Demonstrates how to use the sbb_oidc plugin.
publish_to: 'none'
version: 3.4.0


environment:
  sdk: '>=3.5.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  sbb_oidc:
    path: ../
  # https://github.com/SchweizerischeBundesbahnen/design_system_flutter
  design_system_flutter:
    git:
      url: https://github.com/SchweizerischeBundesbahnen/design_system_flutter.git
      ref: 2.0.0
  # https://pub.dev/packages/collection
  collection: ^1.18.0
  # https://pub.dev/packages/fimber
  fimber: ^0.7.0
  # https://pub.dev/packages/flutter_dotenv
  flutter_dotenv: ^5.1.0
  # https://pub.dev/packages/flutter_json_view
  flutter_json_view: ^1.1.5
  # https://pub.dev/packages/get_it
  get_it: ^7.7.0
  # https://pub.dev/packages/http
  http: ^1.2.2
  # https://pub.dev/packages/meta
  meta: ^1.15.0
  # https://pub.dev/packages/rxdart
  rxdart: ^0.28.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/esq_mobile_dev.env
    - assets/example_app.env
