org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# TODO: remove once the Flutter Gradle plugin supports AGP 9's new DSL (https://developer.android.com/build/releases/agp-9-0-0-release-notes)
android.newDsl=false
# TODO: remove once Flutter's KGP version check recognizes AGP 9's built-in Kotlin version override
skipDependencyChecks=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
