name: sbb_oidc
description: SBB OpenID Connect package for Flutter
homepage: https://github.com/SchweizerischeBundesbahnen/flutter-oidc
publish_to: none
version: 4.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/collection
  collection: ^1.19.0
  # https://pub.dev/packages/flutter_appauth
  flutter_appauth: ^8.0.3
  # https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^9.2.3
  # https://pub.dev/packages/http
  http: ^1.2.2
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0
  # https://pub.dev/packages/meta
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # https://pub.dev/packages/build_runner
  build_runner: ^2.4.14
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^5.0.0
  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.9.2
  # https://pub.dev/packages/mockito
  mockito: ^5.4.5
