name: sbb_oidc
description: SBB OpenID Connect package for Flutter
homepage: https://github.com/SchweizerischeBundesbahnen/flutter-oidc
repository: https://github.com/SchweizerischeBundesbahnen/flutter-oidc
issue_tracker: https://github.com/SchweizerischeBundesbahnen/flutter-oidc/issues
topics: [ authentication, oidc ]
version: 4.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/collection
  collection: ^1.19.1
  # https://pub.dev/packages/flutter_appauth
  flutter_appauth: ^9.0.1
  # https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^9.2.4
  # https://pub.dev/packages/http
  http: ^1.4.0
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0
  # https://pub.dev/packages/meta
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # https://pub.dev/packages/build_runner
  build_runner: ^2.5.3
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^6.0.0
  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.9.5
  # https://pub.dev/packages/mockito
  mockito: ^5.4.6
