name: sbb_oidc_platform_interface
description: A common platform interface for the sbb_oidc plugin.
homepage: https://code.sbb.ch/projects/KD_FLUTTER/repos/esta_mobile_flutter_oidc
publish_to: none
version: 3.3.0


environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/collection
  collection: ^1.18.0
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0
  # https://pub.dev/packages/meta
  meta: ^1.12.0
  # https://pub.dev/packages/plugin_platform_interface
  plugin_platform_interface: ^2.1.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  # https://pub.dev/packages/build_runner
  build_runner: ^2.4.11
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^4.0.0
  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.8.0
