// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package ch.sbb.appbakery.oidc

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object SBBOidcApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class InitializeParameters (
  val clientId: String,
  val keychainAccessGroup: String,
  val redirectUri: String,
  val tenantId: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InitializeParameters {
      val clientId = pigeonVar_list[0] as String
      val keychainAccessGroup = pigeonVar_list[1] as String
      val redirectUri = pigeonVar_list[2] as String
      val tenantId = pigeonVar_list[3] as String
      return InitializeParameters(clientId, keychainAccessGroup, redirectUri, tenantId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      clientId,
      keychainAccessGroup,
      redirectUri,
      tenantId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as InitializeParameters
    return SBBOidcApiPigeonUtils.deepEquals(this.clientId, other.clientId) && SBBOidcApiPigeonUtils.deepEquals(this.keychainAccessGroup, other.keychainAccessGroup) && SBBOidcApiPigeonUtils.deepEquals(this.redirectUri, other.redirectUri) && SBBOidcApiPigeonUtils.deepEquals(this.tenantId, other.tenantId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SBBOidcApiPigeonUtils.deepHash(this.clientId)
    result = 31 * result + SBBOidcApiPigeonUtils.deepHash(this.keychainAccessGroup)
    result = 31 * result + SBBOidcApiPigeonUtils.deepHash(this.redirectUri)
    result = 31 * result + SBBOidcApiPigeonUtils.deepHash(this.tenantId)
    return result
  }
  override fun toString(): String {
    return "InitializeParameters(clientId=$clientId, keychainAccessGroup=$keychainAccessGroup, redirectUri=$redirectUri, tenantId=$tenantId)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LoginParameters (
  val loginHint: String? = null,
  val prompt: String? = null,
  val scopes: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LoginParameters {
      val loginHint = pigeonVar_list[0] as String?
      val prompt = pigeonVar_list[1] as String?
      val scopes = pigeonVar_list[2] as List<String>
      return LoginParameters(loginHint, prompt, scopes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      loginHint,
      prompt,
      scopes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LoginParameters
    return SBBOidcApiPigeonUtils.deepEquals(this.loginHint, other.loginHint) && SBBOidcApiPigeonUtils.deepEquals(this.prompt, other.prompt) && SBBOidcApiPigeonUtils.deepEquals(this.scopes, other.scopes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SBBOidcApiPigeonUtils.deepHash(this.loginHint)
    result = 31 * result + SBBOidcApiPigeonUtils.deepHash(this.prompt)
    result = 31 * result + SBBOidcApiPigeonUtils.deepHash(this.scopes)
    return result
  }
  override fun toString(): String {
    return "LoginParameters(loginHint=$loginHint, prompt=$prompt, scopes=$scopes)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GetTokenParameters (
  val forceRefresh: Boolean,
  val scopes: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GetTokenParameters {
      val forceRefresh = pigeonVar_list[0] as Boolean
      val scopes = pigeonVar_list[1] as List<String>
      return GetTokenParameters(forceRefresh, scopes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      forceRefresh,
      scopes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GetTokenParameters
    return SBBOidcApiPigeonUtils.deepEquals(this.forceRefresh, other.forceRefresh) && SBBOidcApiPigeonUtils.deepEquals(this.scopes, other.scopes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SBBOidcApiPigeonUtils.deepHash(this.forceRefresh)
    result = 31 * result + SBBOidcApiPigeonUtils.deepHash(this.scopes)
    return result
  }
  override fun toString(): String {
    return "GetTokenParameters(forceRefresh=$forceRefresh, scopes=$scopes)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OidcTokenResponse (
  val accessToken: String,
  val authenticationScheme: String,
  val expiresOn: String? = null,
  val idToken: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OidcTokenResponse {
      val accessToken = pigeonVar_list[0] as String
      val authenticationScheme = pigeonVar_list[1] as String
      val expiresOn = pigeonVar_list[2] as String?
      val idToken = pigeonVar_list[3] as String?
      return OidcTokenResponse(accessToken, authenticationScheme, expiresOn, idToken)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      accessToken,
      authenticationScheme,
      expiresOn,
      idToken,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OidcTokenResponse
    return SBBOidcApiPigeonUtils.deepEquals(this.accessToken, other.accessToken) && SBBOidcApiPigeonUtils.deepEquals(this.authenticationScheme, other.authenticationScheme) && SBBOidcApiPigeonUtils.deepEquals(this.expiresOn, other.expiresOn) && SBBOidcApiPigeonUtils.deepEquals(this.idToken, other.idToken)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SBBOidcApiPigeonUtils.deepHash(this.accessToken)
    result = 31 * result + SBBOidcApiPigeonUtils.deepHash(this.authenticationScheme)
    result = 31 * result + SBBOidcApiPigeonUtils.deepHash(this.expiresOn)
    result = 31 * result + SBBOidcApiPigeonUtils.deepHash(this.idToken)
    return result
  }
  override fun toString(): String {
    return "OidcTokenResponse(accessToken=$accessToken, authenticationScheme=$authenticationScheme, expiresOn=$expiresOn, idToken=$idToken)"
  }
}
private open class SBBOidcApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InitializeParameters.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LoginParameters.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GetTokenParameters.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OidcTokenResponse.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is InitializeParameters -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is LoginParameters -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is GetTokenParameters -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is OidcTokenResponse -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SBBOidcHostApi {
  suspend fun initialize(parameters: InitializeParameters)
  suspend fun login(parameters: LoginParameters): OidcTokenResponse
  suspend fun getToken(parameters: GetTokenParameters): OidcTokenResponse
  suspend fun logout()
  suspend fun endSession()

  companion object {
    /** The codec used by SBBOidcHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      SBBOidcApiPigeonCodec()
    }
    /** Sets up an instance of `SBBOidcHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SBBOidcHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sbb_oidc.SBBOidcHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val parametersArg = args[0] as InitializeParameters
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.initialize(parametersArg)
                listOf(null)
              } catch (exception: Throwable) {
                SBBOidcApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sbb_oidc.SBBOidcHostApi.login$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val parametersArg = args[0] as LoginParameters
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.login(parametersArg))
              } catch (exception: Throwable) {
                SBBOidcApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sbb_oidc.SBBOidcHostApi.getToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val parametersArg = args[0] as GetTokenParameters
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getToken(parametersArg))
              } catch (exception: Throwable) {
                SBBOidcApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sbb_oidc.SBBOidcHostApi.logout$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.logout()
                listOf(null)
              } catch (exception: Throwable) {
                SBBOidcApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sbb_oidc.SBBOidcHostApi.endSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.endSession()
                listOf(null)
              } catch (exception: Throwable) {
                SBBOidcApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
