// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum SBBOidcApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct InitializeParameters: Hashable, CustomStringConvertible {
  var clientId: String
  var keychainAccessGroup: String
  var redirectUri: String
  var tenantId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> InitializeParameters? {
    let clientId = pigeonVar_list[0] as! String
    let keychainAccessGroup = pigeonVar_list[1] as! String
    let redirectUri = pigeonVar_list[2] as! String
    let tenantId = pigeonVar_list[3] as! String

    return InitializeParameters(
      clientId: clientId,
      keychainAccessGroup: keychainAccessGroup,
      redirectUri: redirectUri,
      tenantId: tenantId
    )
  }
  func toList() -> [Any?] {
    return [
      clientId,
      keychainAccessGroup,
      redirectUri,
      tenantId,
    ]
  }
  static func == (lhs: InitializeParameters, rhs: InitializeParameters) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SBBOidcApiPigeonInternal.deepEquals(lhs.clientId, rhs.clientId) && SBBOidcApiPigeonInternal.deepEquals(lhs.keychainAccessGroup, rhs.keychainAccessGroup) && SBBOidcApiPigeonInternal.deepEquals(lhs.redirectUri, rhs.redirectUri) && SBBOidcApiPigeonInternal.deepEquals(lhs.tenantId, rhs.tenantId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("InitializeParameters")
    SBBOidcApiPigeonInternal.deepHash(value: clientId, hasher: &hasher)
    SBBOidcApiPigeonInternal.deepHash(value: keychainAccessGroup, hasher: &hasher)
    SBBOidcApiPigeonInternal.deepHash(value: redirectUri, hasher: &hasher)
    SBBOidcApiPigeonInternal.deepHash(value: tenantId, hasher: &hasher)
  }

  public var description: String {
    return "InitializeParameters(clientId: \(String(describing: clientId)), keychainAccessGroup: \(String(describing: keychainAccessGroup)), redirectUri: \(String(describing: redirectUri)), tenantId: \(String(describing: tenantId)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LoginParameters: Hashable, CustomStringConvertible {
  var loginHint: String? = nil
  var prompt: String? = nil
  var scopes: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LoginParameters? {
    let loginHint: String? = nilOrValue(pigeonVar_list[0])
    let prompt: String? = nilOrValue(pigeonVar_list[1])
    let scopes = pigeonVar_list[2] as! [String]

    return LoginParameters(
      loginHint: loginHint,
      prompt: prompt,
      scopes: scopes
    )
  }
  func toList() -> [Any?] {
    return [
      loginHint,
      prompt,
      scopes,
    ]
  }
  static func == (lhs: LoginParameters, rhs: LoginParameters) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SBBOidcApiPigeonInternal.deepEquals(lhs.loginHint, rhs.loginHint) && SBBOidcApiPigeonInternal.deepEquals(lhs.prompt, rhs.prompt) && SBBOidcApiPigeonInternal.deepEquals(lhs.scopes, rhs.scopes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LoginParameters")
    SBBOidcApiPigeonInternal.deepHash(value: loginHint, hasher: &hasher)
    SBBOidcApiPigeonInternal.deepHash(value: prompt, hasher: &hasher)
    SBBOidcApiPigeonInternal.deepHash(value: scopes, hasher: &hasher)
  }

  public var description: String {
    return "LoginParameters(loginHint: \(String(describing: loginHint)), prompt: \(String(describing: prompt)), scopes: \(String(describing: scopes)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct GetTokenParameters: Hashable, CustomStringConvertible {
  var forceRefresh: Bool
  var scopes: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GetTokenParameters? {
    let forceRefresh = pigeonVar_list[0] as! Bool
    let scopes = pigeonVar_list[1] as! [String]

    return GetTokenParameters(
      forceRefresh: forceRefresh,
      scopes: scopes
    )
  }
  func toList() -> [Any?] {
    return [
      forceRefresh,
      scopes,
    ]
  }
  static func == (lhs: GetTokenParameters, rhs: GetTokenParameters) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SBBOidcApiPigeonInternal.deepEquals(lhs.forceRefresh, rhs.forceRefresh) && SBBOidcApiPigeonInternal.deepEquals(lhs.scopes, rhs.scopes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GetTokenParameters")
    SBBOidcApiPigeonInternal.deepHash(value: forceRefresh, hasher: &hasher)
    SBBOidcApiPigeonInternal.deepHash(value: scopes, hasher: &hasher)
  }

  public var description: String {
    return "GetTokenParameters(forceRefresh: \(String(describing: forceRefresh)), scopes: \(String(describing: scopes)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OidcTokenResponse: Hashable, CustomStringConvertible {
  var accessToken: String
  var authenticationScheme: String
  var expiresOn: String? = nil
  var idToken: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OidcTokenResponse? {
    let accessToken = pigeonVar_list[0] as! String
    let authenticationScheme = pigeonVar_list[1] as! String
    let expiresOn: String? = nilOrValue(pigeonVar_list[2])
    let idToken: String? = nilOrValue(pigeonVar_list[3])

    return OidcTokenResponse(
      accessToken: accessToken,
      authenticationScheme: authenticationScheme,
      expiresOn: expiresOn,
      idToken: idToken
    )
  }
  func toList() -> [Any?] {
    return [
      accessToken,
      authenticationScheme,
      expiresOn,
      idToken,
    ]
  }
  static func == (lhs: OidcTokenResponse, rhs: OidcTokenResponse) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SBBOidcApiPigeonInternal.deepEquals(lhs.accessToken, rhs.accessToken) && SBBOidcApiPigeonInternal.deepEquals(lhs.authenticationScheme, rhs.authenticationScheme) && SBBOidcApiPigeonInternal.deepEquals(lhs.expiresOn, rhs.expiresOn) && SBBOidcApiPigeonInternal.deepEquals(lhs.idToken, rhs.idToken)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OidcTokenResponse")
    SBBOidcApiPigeonInternal.deepHash(value: accessToken, hasher: &hasher)
    SBBOidcApiPigeonInternal.deepHash(value: authenticationScheme, hasher: &hasher)
    SBBOidcApiPigeonInternal.deepHash(value: expiresOn, hasher: &hasher)
    SBBOidcApiPigeonInternal.deepHash(value: idToken, hasher: &hasher)
  }

  public var description: String {
    return "OidcTokenResponse(accessToken: \(String(describing: accessToken)), authenticationScheme: \(String(describing: authenticationScheme)), expiresOn: \(String(describing: expiresOn)), idToken: \(String(describing: idToken)))"
  }
}

private class SBBOidcApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return InitializeParameters.fromList(self.readValue() as! [Any?])
    case 130:
      return LoginParameters.fromList(self.readValue() as! [Any?])
    case 131:
      return GetTokenParameters.fromList(self.readValue() as! [Any?])
    case 132:
      return OidcTokenResponse.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class SBBOidcApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? InitializeParameters {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? LoginParameters {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? GetTokenParameters {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? OidcTokenResponse {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class SBBOidcApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return SBBOidcApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return SBBOidcApiPigeonCodecWriter(data: data)
  }
}

class SBBOidcApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = SBBOidcApiPigeonCodec(readerWriter: SBBOidcApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SBBOidcHostApi {
  func initialize(parameters: InitializeParameters) async throws
  func login(parameters: LoginParameters) async throws -> OidcTokenResponse
  func getToken(parameters: GetTokenParameters) async throws -> OidcTokenResponse
  func logout() async throws
  func endSession() async throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SBBOidcHostApiSetup {
  static var codec: FlutterStandardMessageCodec { SBBOidcApiPigeonCodec.shared }
  /// Sets up an instance of `SBBOidcHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SBBOidcHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sbb_oidc.SBBOidcHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let parametersArg = args[0] as! InitializeParameters
        Task { @MainActor in
          do {
            try await api.initialize(parameters: parametersArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let loginChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sbb_oidc.SBBOidcHostApi.login\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loginChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let parametersArg = args[0] as! LoginParameters
        Task { @MainActor in
          do {
            let result = try await api.login(parameters: parametersArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      loginChannel.setMessageHandler(nil)
    }
    let getTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sbb_oidc.SBBOidcHostApi.getToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let parametersArg = args[0] as! GetTokenParameters
        Task { @MainActor in
          do {
            let result = try await api.getToken(parameters: parametersArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getTokenChannel.setMessageHandler(nil)
    }
    let logoutChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sbb_oidc.SBBOidcHostApi.logout\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      logoutChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.logout()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      logoutChannel.setMessageHandler(nil)
    }
    let endSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sbb_oidc.SBBOidcHostApi.endSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      endSessionChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.endSession()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      endSessionChannel.setMessageHandler(nil)
    }
  }
}
