name: sbb_oidc_mobile
description: Mobile (Android and iOS) implementation of the sbb_oidc plugin.
homepage: https://github.com/SchweizerischeBundesbahnen/flutter-oidc
publish_to: none
version: 3.3.0


environment:
  sdk: '>=3.5.2 <4.0.0'


flutter:
  plugin:
    implements: sbb_oidc
    platforms:
      android:
        dartPluginClass: SBBOidcMobile
        dartFileName: sbb_oidc_mobile.dart
      ios:
        dartPluginClass: SBBOidcMobile
        dartFileName: sbb_oidc_mobile.dart


dependencies:
  flutter:
    sdk: flutter
  sbb_oidc_platform_interface:
    git:
      url: https://github.com/SchweizerischeBundesbahnen/flutter-oidc.git
      path: sbb_oidc_platform_interface
      ref: 3.3.0
  # https://pub.dev/packages/flutter_appauth
  flutter_appauth: ^7.0.0
  # https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^9.2.2
  # https://pub.dev/packages/http
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^4.0.0
