name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Ensure that new pushes/updates cancel running jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.4
          cache: true
      - run: flutter pub get
      - run: flutter test
